"""
Django settings for preachingSacco project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env_file = BASE_DIR.parent / '.env'
if env_file.exists():
    for line in env_file.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith('#') and '=' in line:
            key, value = line.split('=', 1)
            os.environ.setdefault(key.strip(), value.strip())


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-change-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        'ALLOWED_HOSTS',
        'localhost,127.0.0.1,sisipamoja.onrender.com'
    ).split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'preachingSacco.auth_config.SisiPamojaAuthConfig',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'sisikwaPamoja',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = 'preachingSacco.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sisikwaPamoja.context_processors.admin_dashboard_context',
            ],
        },
    },
    
]

WSGI_APPLICATION = 'preachingSacco.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get(
            'DATABASE_URL',
            'postgres://postgres:2027@localhost:5432/Sacco_db'
        ),
        conn_max_age=600,
    )
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

#Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.environ.get('MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))
AUTH_USER_MODEL = 'sisikwaPamoja.CustomUser'

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

JAZZMIN_SETTINGS = {
    # ── Brand ──────────────────────────────────────────────
    "site_title": "SisiPamoja Welfare",
    "site_header": "SisiPamoja Welfare Admin",
    "site_brand": "SisiPamoja Welfare",
    "site_logo": "images/LOGO.jpeg",  # put logo in static/images/
    "site_logo_classes": "img-circle elevation-3",
    "site_icon": "images/LOGO.jpeg",
    "welcome_sign": "Together in Times of Need",
    "show_version": False,
    # Keep this empty to avoid double-printing when we override the footer in templates
    "copyright": "",

    # ── Top Menu ───────────────────────────────────────────
    "topmenu_links": [
        {
            "name": "Dashboard",
            "url": "/admin/",
        },
        {
            "name": "View Site",
            "url": "/",
            "new_window": True
        },
        {
            "name": "Members",
            "url": "/admin/sisikwaPamoja/memberprofile/",
        },
        {
            "name": "Contributions",
            "url": "/admin/sisikwaPamoja/contribution/",
        },
    ],

    "usermenu_links": [],
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [
        "sisikwapamoja.customuser",
    ],
    "order_with_respect_to": [
        "sisikwapamoja",
        "sisikwapamoja.memberprofile",
        "sisikwapamoja.contribution",
        "sisikwapamoja.spouse",
        "sisikwapamoja.dependant",
        "sisikwapamoja.serialnumbertracker",
        "auth",
        "auth.User",
        "auth.Group",
        "sisikwapamoja.Lastexpense",
    ],

    "custom_links": {
        "auth": [
            {
                "name": "Users",
                "url": "/admin/sisikwaPamoja/customuser/",
                "icon": "fas fa-user",
                "permissions": ["sisikwaPamoja.view_customuser"],
            },
        ],
    },

    # ── Sidebar Icons ──────────────────────────────────────
    "icons": {
        "auth": "fas fa-lock",
        "auth.user": "fas fa-user-tie",
        "auth.group": "fas fa-users-cog",
        "sisikwaPamoja": "fas fa-church",
        "sisikwaPamoja.MemberProfile": "fas fa-id-card",
        "sisikwaPamoja.Contribution": "fas fa-money-bill-wave",
        "sisikwaPamoja.Spouse": "fas fa-heart",
        "sisikwaPamoja.Dependant": "fas fa-child",
        "sisikwaPamoja.SerialNumberTracker": "fas fa-list-ol",
    },

    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    # ── UI Tweaks ──────────────────────────────────────────
    "related_modal_active": True,
    "custom_css": "css/admin_custom.css",
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,

    # ── Colors matching your theme ─────────────────────────
    "brand_colour": "navbar-success",      # green navbar brand
    "accent": "accent-warning",            # golden yellow accents
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-success",     # dark green sidebar
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-success",          # green primary buttons
        "secondary": "btn-warning",        # golden secondary
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "dark": "btn-dark",
    },
}


# MPESA Configuration
MPESA_ENVIRONMENT = os.environ.get('MPESA_ENVIRONMENT', 'sandbox')
MPESA_SHORTCODE = os.environ.get('MPESA_SHORTCODE', '174379')
MPESA_CONSUMER_KEY = os.environ.get('MPESA_CONSUMER_KEY', '')
MPESA_CONSUMER_SECRET = os.environ.get('MPESA_CONSUMER_SECRET', '')
MPESA_PASSKEY = os.environ.get('MPESA_PASSKEY', '')
MPESA_CALLBACK_URL = os.environ.get('MPESA_CALLBACK_URL', 'https://example.com/mpesa/callback/')

# ══════════════════════════════════════
# AFRICA'S TALKING SMS SETTINGS
# ══════════════════════════════════════
AT_USERNAME = os.environ.get('AT_USERNAME', 'sandbox')
AT_API_KEY = os.environ.get('AT_API_KEY', '')
AT_SENDER_ID = os.environ.get('AT_SENDER_ID') or None
