# Generated by Django 6.0.5 on 2026-05-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisikwaPamoja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spouse',
            name='full_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
