# Generated by Django 6.0.5 on 2026-05-20 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisikwaPamoja', '0002_memberprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='contribution_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='member_type',
            field=models.CharField(choices=[('last_expense', 'Last Expense Member'), ('sacco', 'Sacco Member')], default='last_expense', max_length=20),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Dependant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('relationship_type', models.CharField(choices=[('child', 'Child'), ('parent', 'Parent'), ('relative', 'Relative'), ('other', 'Other')], max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('identification_number', models.CharField(max_length=50)),
                ('supporting_document', models.FileField(upload_to='dependant_documents/')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependants', to='sisikwaPamoja.memberprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SpouseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('county_of_birth', models.CharField(max_length=100)),
                ('sub_county_of_birth', models.CharField(max_length=100)),
                ('id_copy', models.FileField(upload_to='spouse_id_copies/')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spouse', to='sisikwaPamoja.memberprofile')),
            ],
        ),
    ]
