# Generated by Django 6.0.5 on 2026-06-19 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisikwaPamoja', '0003_mpesapayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('event_type', models.CharField(choices=[('account_created', 'Account Created'), ('member_approved', 'Member Approved'), ('dependant_added', 'Dependant Added'), ('contribution_received', 'Contribution Received'), ('mpesa_success', 'M-Pesa Payment Success'), ('loan_applied', 'Loan Applied'), ('loan_approved', 'Loan Approved'), ('loan_rejected', 'Loan Rejected'), ('password_reset', 'Password Reset OTP')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('at_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('at_cost', models.CharField(blank=True, max_length=20, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='sisikwaPamoja.memberprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
