# Generated by Django 6.0.5 on 2026-06-30 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisikwaPamoja', '0004_smslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_business_name', models.CharField(blank=True, max_length=200, null=True)),
                ('occupation', models.CharField(blank=True, max_length=150, null=True)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_product', models.CharField(choices=[('development', 'Development Loan'), ('emergency', 'Emergency Loan'), ('school_fees', 'School Fees Loan'), ('business', 'Business Loan'), ('asset_finance', 'Asset Finance Loan'), ('salary_advance', 'Salary Advance'), ('other', 'Other')], max_length=30)),
                ('loan_product_other', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_applied', models.DecimalField(decimal_places=2, max_digits=12)),
                ('repayment_period_months', models.IntegerField()),
                ('proposed_monthly_installment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose_of_loan', models.TextField()),
                ('security_offered', models.CharField(choices=[('savings', 'Deposits/Savings'), ('guarantors', 'Guarantors'), ('logbook', 'Logbook'), ('title_deed', 'Title Deed'), ('other', 'Other')], max_length=20)),
                ('security_other', models.CharField(blank=True, max_length=100, null=True)),
                ('current_sacco_savings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('disbursement_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('mpesa', 'M-Pesa')], max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=150, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=150, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('mpesa_registered_name', models.CharField(blank=True, max_length=150, null=True)),
                ('mpesa_number', models.CharField(blank=True, max_length=15, null=True)),
                ('id_copy', models.FileField(blank=True, null=True, upload_to='loan_documents/ids/')),
                ('payslip_or_statement', models.FileField(blank=True, null=True, upload_to='loan_documents/payslips/')),
                ('business_permit', models.FileField(blank=True, null=True, upload_to='loan_documents/permits/')),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='loan_documents/supporting/')),
                ('digital_signature', models.CharField(help_text='Typed full name as signature', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='sisikwaPamoja.memberprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanGuarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('membership_number', models.CharField(blank=True, max_length=50, null=True)),
                ('national_id', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=15)),
                ('amount_guaranteed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_copy', models.FileField(blank=True, null=True, upload_to='loan_documents/guarantor_ids/')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='sisikwaPamoja.loanapplication')),
            ],
        ),
    ]
