# Generated by Django 6.0.5 on 2026-06-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisikwaPamoja', '0005_loanapplication_loanguarantor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='event_type',
            field=models.CharField(choices=[('account_created', 'Account Created'), ('member_approved', 'Member Approved'), ('dependant_added', 'Dependant Added'), ('contribution_received', 'Contribution Received'), ('mpesa_success', 'M-Pesa Payment Success'), ('loan_applied', 'Loan Applied'), ('loan_approved', 'Loan Approved'), ('loan_rejected', 'Loan Rejected'), ('loan_disbursed', 'Loan Disbursed'), ('password_reset', 'Password Reset OTP')], max_length=30),
        ),
    ]
