# Generated by Django 6.0.5 on 2026-07-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisikwaPamoja', '0007_memberprofile_annual_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberpayment',
            name='description',
            field=models.CharField(blank=True, help_text='Reason for payment', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='memberpayment',
            name='payment_type',
            field=models.CharField(choices=[('registration', 'Registration Fee'), ('capital_share', 'Capital Share'), ('annual', 'Annual Welfare Contribution'), ('contribution', 'Monthly Contribution')], max_length=20),
        ),
    ]
