# Generated by Django 6.0.5 on 2026-07-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisikwaPamoja', '0008_memberpayment_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('payment', 'Payment'), ('loan', 'Loan'), ('agm', 'AGM / Meeting'), ('maintenance', 'Maintenance'), ('alert', 'Alert')], default='general', max_length=20)),
                ('color', models.CharField(choices=[('green', 'Green'), ('orange', 'Orange'), ('blue', 'Blue'), ('gold', 'Gold')], default='green', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from members')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
