# Generated by Django 6.0.5 on 2026-07-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisikwaPamoja', '0009_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='KRA PIN'),
        ),
    ]
