# Generated by Django 6.0.5 on 2026-07-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisikwaPamoja', '0010_memberprofile_kra_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberpayment',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('admin', 'Admin Approval')], default='admin', max_length=20),
        ),
    ]
